env: local
migrations_path: ./migrations

database:
  host: db
  port: 5432
  user: vlt-user
  password: vault333
  name: Vault
  sslmode: disable
  attemps: 5
  delay: 5s
  timeout: 5s

http-server:
  port: 8200
  timeout: 5s
  idle_timeout: 60s
